#set document(title: "Analisis de Saldos por Cobrar", author: "Facturazo ERP")
#set page(paper: "us-letter", margin: (top: 10mm, bottom: 10mm, left: 8mm, right: 8mm), numbering: "1 / 1")
#set text(font: "Inter", size: 8.549999999999999pt)
#set par(justify: false)

// Header
#align(center)[
  #text(size: 14pt, weight: "bold")[Analisis de Saldos por Cobrar]
  #v(2pt)
  #text(size: 9pt, fill: gray)[Cuentas por Cobrar / Reportes / Analisis de Saldos]
]
#v(8pt)
#line(length: 100%, stroke: 1pt + rgb(24, 144, 255))
#v(8pt)

// Filters
#rect(width: 100%, fill: rgb(250, 250, 250), stroke: 0.5pt + rgb(200, 200, 200), radius: 2pt, inset: 6pt)[
  #text(size: 8pt, fill: gray)[Al: 15/12/2025]
]
#v(8pt)

// Data
#table(
  columns: (80pt, 200pt, 100pt, 90pt, 110pt, 100pt, 100pt, 100pt, 100pt),
  stroke: 0.5pt + rgb(220, 220, 220),
  fill: (x, y) => if y == 0 { rgb(245, 245, 245) } else if calc.odd(y) { rgb(252, 252, 252) } else { white },
  inset: 5pt,
  table.cell(align: left)[#text(weight: "bold", size: 8pt)[Codigo]],
    table.cell(align: left)[#text(weight: "bold", size: 8pt)[Cliente]],
    table.cell(align: left)[#text(weight: "bold", size: 8pt)[Documento]],
    table.cell(align: center)[#text(weight: "bold", size: 8pt)[Vencimiento]],
    table.cell(align: right)[#text(weight: "bold", size: 8pt)[Saldo]],
    table.cell(align: right)[#text(weight: "bold", size: 8pt)[Corriente]],
    table.cell(align: right)[#text(weight: "bold", size: 8pt)[1-30 dias]],
    table.cell(align: right)[#text(weight: "bold", size: 8pt)[31-60 dias]],
    table.cell(align: right)[#text(weight: "bold", size: 8pt)[61+ dias]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0001]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 1 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000001]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[01/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[5,000.00]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[5,000.00]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0002]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 2 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000002]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[02/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[5,234.56]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[5,234.56]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0003]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 3 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000003]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[03/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[5,469.12]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[5,469.12]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0004]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 4 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000004]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[04/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[5,703.68]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[5,703.68]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0005]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 5 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000005]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[05/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[5,938.24]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[5,938.24]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0006]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 6 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000006]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[06/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[6,172.80]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[6,172.80]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0007]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 7 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000007]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[07/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[6,407.36]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[6,407.36]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0008]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 8 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000008]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[08/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[6,641.92]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[6,641.92]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0009]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 9 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000009]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[09/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[6,876.48]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[6,876.48]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0010]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 10 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000010]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[10/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[7,111.04]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[7,111.04]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0011]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 11 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000011]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[11/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[7,345.60]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[7,345.60]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0012]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 12 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000012]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[12/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[7,580.16]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[7,580.16]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0013]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 13 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000013]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[13/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[7,814.72]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[7,814.72]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0014]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 14 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000014]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[14/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[8,049.28]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[8,049.28]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0015]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 15 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000015]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[15/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[8,283.84]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[8,283.84]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0016]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 16 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000016]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[16/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[8,518.40]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[8,518.40]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0017]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 17 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000017]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[17/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[8,752.96]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[8,752.96]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0018]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 18 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000018]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[18/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[8,987.52]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[8,987.52]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0019]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 19 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000019]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[19/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[9,222.08]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[9,222.08]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0020]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 20 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000020]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[20/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[9,456.64]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[9,456.64]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0021]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 21 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000021]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[21/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[9,691.20]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[9,691.20]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0022]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 22 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000022]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[22/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[9,925.76]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[9,925.76]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0023]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 23 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000023]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[23/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[10,160.32]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[10,160.32]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0024]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 24 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000024]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[24/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[10,394.88]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[10,394.88]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0025]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 25 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000025]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[25/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[10,629.44]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[10,629.44]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0026]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 26 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000026]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[26/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[10,864.00]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[10,864.00]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0027]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 27 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000027]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[27/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[11,098.56]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[11,098.56]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0028]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 28 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000028]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[28/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[11,333.12]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[11,333.12]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0029]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 29 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000029]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[01/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[11,567.68]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[11,567.68]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]],
  table.cell(align: left)[#text(weight: "regular", size: 7pt)[CLI-0030]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[Empresa 30 S.R.L.]],
    table.cell(align: left)[#text(weight: "regular", size: 7pt)[FAC-000030]],
    table.cell(align: center)[#text(weight: "regular", size: 7pt)[02/12/2025]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt, fill: rgb(24, 144, 255))[11,802.24]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[11,802.24]],
    table.cell(align: right)[#text(weight: "regular", size: 7pt)[-]],
    table.cell(align: right)[#text(weight: "bold", size: 7pt)[-]]
)

// Grand Total

#v(12pt)
#rect(width: 100%, fill: rgb(240, 245, 250), stroke: 1.5pt + rgb(24, 144, 255), radius: 4pt, inset: 10pt)[
  #grid(columns: (auto, 1fr), gutter: 5pt,
    [#text(weight: "bold", size: 11pt, fill: rgb(24, 144, 255))[TOTAL GENERAL]],
    [#text(size: 9pt, fill: gray)[(30 registros)]],
  )
  #v(8pt)
  #grid(columns: (150pt, auto), gutter: 4pt,
    [Saldo:], [#text(weight: "bold")[252,033.60]]
  )
]

// Footer
#v(1fr)
#line(length: 100%, stroke: 0.5pt + rgb(200, 200, 200))
#v(3pt)
#grid(columns: (1fr, 1fr), gutter: 0pt,
  [#text(size: 7pt, fill: gray)[Generado: 2025-12-15T07:33:30.392491+00:00]],
  [#align(right)[#text(size: 7pt, fill: gray)[Pagina #context counter(page).display() de #context counter(page).final().at(0)]]]
)